services:
    nginx:
      container_name: nginx
      build: ./requirements/nginx
      volumes:
        - ./src:/var/www/html
      networks:
        - webserver_net
      ports:
        - "443:443"
        - "80:80"
      env_file:
        - .env
      depends_on:
        - phpfpm
      restart: on-failure
    
    phpfpm:
      container_name: phpfpm
      build: ./requirements/fpm
      volumes:
        - ./src:/var/www/html
      networks:
        - webserver_net
      environment:
        MAGE_MODE: ${APP_MAGE_MODE}
      restart: on-failure
    
    db:
      container_name: db
      image: mariadb:10.4
      ports:
        - "3306:3306"
      env_file:
        - .env
      volumes:
        - dbdata:/var/lib/mysql
      networks:
        - webserver_net
      restart: on-failure

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
        - xpack.security.enabled=false
        - cluster.routing.allocation.disk.threshold_enabled=false
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - webserver_net
      restart: on-failure

networks:
  webserver_net:
    driver: bridge

volumes:
  dbdata: