services:
    nginx:
      container_name: nginx
      build: ./requirements/nginx
      volumes:
        - ./src:/var/www/html
      networks:
        - webserver_net
      ports:
        - "443:443"
        - "80:80"
      env_file:
        - .env
      depends_on:
        - phpfpm
      restart: on-failure
    
    phpfpm:
      container_name: phpfpm
      build: ./requirements/fpm
      volumes:
        - ./src:/var/www/html
      networks:
        - webserver_net
      environment:
        MAGE_MODE: ${APP_MAGE_MODE}
      restart: on-failure
    
    db:
      container_name: db
      image: mariadb:10.4
      ports:
        - "3306:3306"
      env_file:
        - .env
      volumes:
        - dockerize_dbdata:/var/lib/mysql
      networks:
        - webserver_net
      restart: on-failure

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
        - xpack.security.enabled=false
        - cluster.routing.allocation.disk.threshold_enabled=false
      ports:
        - "9200:9200"
      networks:
        - webserver_net
      restart: on-failure

networks:
  webserver_net:
    driver: bridge

# If you want to use the existing volume like "docerize_dbdata". I know about typos :)
volumes:
  dockerize_dbdata:
    external: true
    name: docerize_dbdata

# you can remove driver_opts directive but if you don't, don't forget to create "device" directory
#  new_volume_name:
#    driver: local
#      driver_opts:
#        device: /home/${USER}/data/mariadb
#        o: bind
#        type: none